public enum AssetSlot
{
    None = 0,
    Hair = 1,
    UpperBody = 2,
    LowerBody = 3,
    Mask = 4,
    Eyes = 5,
    Mouth = 6,
    Hats = 7,
    Skin = 8,
    Beard = 9,
    Special = 10,
    Achievements = 11,
    AnimationWin = 12,
    AnimationEmoteConfused = 13,
    AnimationEmoteCry = 14,
    AnimationEmoteGG = 15,
    AnimationEmoteHappy = 16,
    AnimationEmoteMindblown = 17,
    AnimationEmoteWave = 18,
    AnimationEmoteCool = 19,
    Companion = 20,
    Handheld = 21,
    Border = 22,
    Background = 23,
}